### ISSUE TITLE
Wrong method called in ItemDetail::loadDetailByItemId

### ISSUE THREAD

**Issue by bmarquis** [shipperhq/module-shipper#10]
This calls is wrong in  \ShipperHQ\Shipper\Model\Order\ItemDetail::loadDetailByItemId
`$this->orderItemDetailCollection->addItemToFilter($itemId);`

It should probably be calling addItem**Id**ToFilter located here \ShipperHQ\Shipper\Model\ResourceModel\Order\ItemDetail\Collection::addItemIdToFilter: 
`$this->orderItemDetailCollection->addItemIdToFilter($itemId);`

Thanks,
Ben

**Comment by wsagen** [comment]
Thanks for raising also, we have a fix going out for this today.

**Comment by wsagen** [comment]
Version 20.1.1 includes fix for this issue
