### ISSUE TITLE
Removing ShipperHQ Breaks Admin Order Edit

### ISSUE THREAD

**Issue by EmperorKonstantin** [shipperhq/module-shipper#102]
Removing Shipper HQ breaks the ability to edit the shipping method for existing orders.

When I go to edit the shipping of an order in admin I get the following:
**Sorry, no quotes are available for this order.**

in exception.log I get the following:
`
[2021-08-30 20:39:30] main.CRITICAL: Class ShipperHQ\Shipper\Model\Customer\Attribute\Source\AddressType does not exist {"report_id":"fb0641a1fd0a9f893d052b493f2f48ccbb1fe9a33979496d3e80e4dc920c43b3","exception":"[object] (ReflectionException(code: -1): Class ShipperHQ\\Shipper\\Model\\Customer\\Attribute\\Source\\AddressType does not exist at /var/www/html/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:26)"} []
`

I also tried to do 
```bash
bin/magento module:uninstall ShipperHQ_Shipper
``` 
with no success.

**Comment by wsadasmit** [comment]
Hi @EmperorKonstantin,

I've just attempted to replicate and did not encounter any issue related to AddressType, instead the attribute has been completely removed by using the command
`php bin/magento module:uninstall -r ShipperHQ_Shipper`
as described in our [uninstall document](https://docs.shipperhq.com/disable-uninstall-magento-extension/#Composer_Uninstaller). The -r flag here causes such data to be removed from the database.

Additionally, when I went to reorder the previous order, on attempting to reestimate shipping I encountered a "Class ... does not exist" error, which was resolved with the troubleshooting steps [here](https://docs.shipperhq.com/troubleshooting-magento-2-installations/#Class_Not_Found).

Can you please try these steps and, if you'd like further assistance troubleshooting this issue, please describe what happens after these steps are taken in an email to support@shipperhq.com.

Thanks!

**Comment by EmperorKonstantin** [comment]
Will do, thanks!

**Comment by EmperorKonstantin** [comment]
@wsadasmit, I ran the uninstall -r command and doublechecked and the tables were still in the database.

I did the following to sanitize:

```sql
drop table shipperhq_order_detail; 
drop table shipperhq_order_detail_grid; 
drop table shipperhq_order_item_detail; 
drop table shipperhq_order_package_items; 
drop table shipperhq_order_packages; 
drop table shipperhq_quote_address_detail; 
drop table shipperhq_quote_address_item_detail; 
drop table shipperhq_quote_item_detail; 
drop table shipperhq_quote_package_items; 
drop table shipperhq_quote_packages; 
drop table shipperhq_synchronize; 

DELETE FROM eav_attribute WHERE attribute_code IN ( 'shipperhq_shipping_group', 'shipperhq_warehouse', 'shipperhq_shipping_fee', 'shipperhq_handling_fee', 'shipperhq_volume_weight', 'shipperhq_declared_value', 'shipperhq_dim_group', 'shipperhq_poss_boxes', 'shipperhq_malleable_product', 'shipperhq_master_boxes', 'shipperhq_availability_date', 'destination_type', 'freight_class', 'shipperhq_nmfc_class', 'must_ship_freight', 'shipperhq_nmfc_sub' ); 

DELETE FROM core_config_data WHERE path='carriers/shqfedex2/model'; 
```
