### ISSUE TITLE
Method to pull Delivery Dates

### ISSUE THREAD

**Issue by pbaum83** [shipperhq/module-shipper#104]
What is the best way to pull the delivery/dispatch date from an order with the shipperhq module installed? Are there are any magic methods on the order interface or is helper that ships with the module to help with this? We have been using a SQL call to pull the values from the shipperhq_order_detail table which isn't ideal.

**Comment by wsadasmit** [comment]
Hi @pbaum83 ,

Here's a link to a document in our KB which mentions the following function you can use to do this:
https://docs.shipperhq.com/integrate-shipperhq-order-management-fulfillment-service-magento/#Magento_2

The function getOrderCarrierGroupInfo($orderId) will output the pieces of data from that array included in the attached screenshot. This function can be found in “ShipperHQ\Shipper\Helper\CarrierGroup”.

For example for the delivery date you should be able to use the following piece of code:
$carrierGroupInfo = $this->carrierGroupHelper->getOrderCarrierGroupInfo($order->getId()); $deliveryDate = $carrierGroupInfo['deivery_date'];
