### ISSUE TITLE
Cannot drop index 'SHIPPERHQ_ORDER_DETAIL_GRID_ORDER_ID': needed in a foreign key constraint

### ISSUE THREAD

**Issue by iindranil** [shipperhq/module-shipper#108]
Hello,

I am getting this error [Cannot drop index 'SHIPPERHQ_ORDER_DETAIL_GRID_ORDER_ID': needed in a foreign key constraint] after upgraded Magento Version 2.3.4 to 2.4.2-p1

Details what I am using:
Magento Version : 2.4.2-p1

"name": "shipperhq/module-shipper"
"version": "20.45.6"

The above issue I am getting while run setup upgrade, If I disabled the module then our Magento running well.

Is there any solution available? Please let me know.

Thank you,

**Comment by wsajosh** [comment]
Thanks for raising this issue. We'll be creating a new release shortly which addresses it. Please update to that new version once its available
