### ISSUE TITLE
Shipping cart total not displayed for multiple shipping methods

### ISSUE THREAD

**Issue by david-fuehr** [shipperhq/module-shipper#109]
**Repro**
1. Ensure that at least two shipping methods are configured active (shipping cost > 0)
2. Add a product to the cart
3. Open cart
    1. *expected* shipping cost is included in grand total; shipping total is visible in totals summary
    1. *actual* shipping cost is included in grand total; shipping total is **not** visible in totals summary

That behaviour was introduced in 2019 (https://github.com/shipperhq/module-shipper/commit/ad2d3b31b1b0521c030f7abd27677dc3d7aece9d#diff-441de581123fb1e95f58a45c0377a5b1eb86febb07842048ef90f7bd2fc56536). Maybe this commit worked as intended two years ago, it seems to me that currently those changes lead to an inconsistent totals overview in cart when multiple shipping methods are enabled.

I would recommend to remove lines 180-186 (https://github.com/shipperhq/module-shipper/blob/main/src/view/frontend/web/js/model/shipping-service-mixin.js#L180).

**Comment by wsadasmit** [comment]
Hi @david-fuehr,

Thanks for this submission, I've scheduled it for review.

**Comment by wsadasmit** [comment]
Hi @david-fuehr,

We're unable to replicate this issue with the steps you provided above. If you're still experiencing this, you can please send a more detailed description of the steps required to replicate, to support@shipperhq.com?

Screenshots of the error or a video demonstration may also be helpful. Thank you,
