### ISSUE TITLE
Error while installing through composer

### ISSUE THREAD

**Issue by wclsandipan** [shipperhq/module-shipper#110]
composer require shipperhq/module-shipper
Using version ^20.45 for shipperhq/module-shipper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals

Installation failed, reverting ./composer.json to its original content.

                                                                                                                                                  
  [Exception]                                                                                                                                     
  Higher matching version 20.45.9 of shipperhq/module-shipper was found in public repository packagist.org                                        
                               than 20.45.5 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,   
                               please investigate and update package requirement to match the version from the private repository                 
                                                                                                                                                  

![image](https://user-images.githubusercontent.com/18529294/146631774-e76b0683-1a4d-4630-b2fd-b452875557a4.png)

**Comment by wsagen** [comment]
Thanks for reporting this, the latest version of module-shipper is now available on Magento. You will be able to install or upgrade without issue now.
