### ISSUE TITLE
Issue while compiling version 20.45.10

### ISSUE THREAD

**Issue by pioneerathletics** [shipperhq/module-shipper#111]
Magento version: 2.4.3 -p1
MySQL version: 5.7
Installation by composer

Updated from version Shipper HQ 20.45.9 to 20.45.10 via composer. Ran setup:upgrade with no issues, but received this error while running setup:di:compile.

`Area configuration aggregation... 5/9 [=======>-----]  55% 50 secs 370.0 MiB
In ClassReader.php line 51:
                                                                               
  Impossible to process constructor argument Parameter #6 [ <required> Shippe  
  rHQ\WS\Shared\BasicAddressFactory $basicAddressFactory ] of ShipperHQ\Shipp  
  er\Helper\PostOrder class                                                    
                                                                               

In ClassReader.php line 71:
                                                                
  Class ShipperHQ\WS\Shared\BasicAddressFactory does not exist  
                                                               `
Please advise.

**Comment by wsajosh** [comment]
Hi @pioneerathletics 

Apologies, it looks like a step in our build process fell over. I've just released 20.45.11 which will resolve this issue. Please update to that version
