### ISSUE TITLE
SQL error updating from 20.47.1 => 20.47.2

### ISSUE THREAD

**Issue by pioneerathletics** [shipperhq/module-shipper#112]
Magento version: 2.4.3-p1
MySQL version: 5.7

Hello,

I received this error after upgrading from 20.47.1 => 20.47.2 and running setup:upgrade:

Updating modules:
Cache cleared successfully
Schema creation/updates:
SQLSTATE[HY000]: General error: 1553 Cannot drop index 'SHIPPERHQ_ORDER_DETAIL_GRID_ORDER_ID': needed in a foreign key constraint, query was: ALTER TABLE `shipperhq_order_detail_grid` DROP KEY `SHIPPERHQ_ORDER_DETAIL_GRID_ORDER_ID`

Note: When I updated to 20.47.1 the other day I had no database issue. It was only updating from 20.47.1 to 20.47.2 where I encountered this.

Thanks

**Comment by ibraheemnabeelfauzi** [comment]
Hello @pioneerathletics , 

Many thanks for the details. We see the cause of the issue and we'll release a fix for it. 

Can you please provide us with your company name?

**Comment by pioneerathletics** [comment]
Hi @ibraheemnabeelfauzi,

I work for Pioneer Athletics and we use the ShipperHQ module on 3 of our websites. Looking forward to the fix for this. Thanks!

**Comment by wsajosh** [comment]
Hi @pioneerathletics Thanks for raising this! I've just released a new version which will address the issue. Please update and let us know if you hit any further issues.
