### ISSUE TITLE
Trouble Installing via Composer on Magento CE 2.3.7

### ISSUE THREAD

**Issue by nickpiro** [shipperhq/module-shipper#113]
Module was causing an issue so I uninstalled (Composer Remove) then reinstalled and receive this error:
Problem 1
    - Installation request for shipperhq/module-shipper 20.47.6 -> satisfiable by shipperhq/module-shipper[20.47.6].
    - Conclusion: don't install shipperhq/module-shipper 20.47.6|remove laminas/laminas-http 2.15.1|install laminas/laminas-http 2.5.0|install zendframework/zend-http 2.0.3|install zendframework/zend-http 2.0.4|install zendframework/zend-http 2.0.5|install zendframework/zend-http 2.0.6|install zendframework/zend-http 2.0.7|install zendframework/zend-http 2.0.8|install zendframework/zend-http 2.1.0|install zendframework/zend-http 2.1.1|install zendframework/zend-http 2.1.2|install zendframework/zend-http 2.1.3|install zendframework/zend-http 2.1.4|install zendframework/zend-http 2.1.5|install zendframework/zend-http 2.1.6|install zendframework/zend-http 2.2.0|install zendframework/zend-http 2.2.0rc1|install zendframework/zend-http 2.2.0rc2|install zendframework/zend-http 2.2.0rc3|install zendframework/zend-http 2.2.1|install zendframework/zend-http 2.2.10|install zendframework/zend-http 2.2.2|install zendframework/zend-http 2.2.3|install zendframework/zend-http 2.2.4|install zendframework/zend-http 2.2.5|install zendframework/zend-http 2.2.6|install zendframework/zend-http 2.2.7|install zendframework/zend-http 2.2.8|install zendframework/zend-http 2.2.9|install zendframework/zend-http 2.3.0|install zendframework/zend-http 2.3.1|install zendframework/zend-http 2.3.2|install zendframework/zend-http 2.3.3|install zendframework/zend-http 2.3.4|install zendframework/zend-http 2.3.5|install zendframework/zend-http 2.3.6|install zendframework/zend-http 2.3.7|install zendframework/zend-http 2.3.8|install zendframework/zend-http 2.3.9|install zendframework/zend-http 2.4.0|install zendframework/zend-http 2.4.0rc1|install zendframework/zend-http 2.4.0rc2|install zendframework/zend-http 2.4.0rc3|install zendframework/zend-http 2.4.0rc4|install zendframework/zend-http 2.4.0rc5|install zendframework/zend-http 2.4.0rc6|install zendframework/zend-http 2.4.0rc7|install zendframework/zend-http 2.4.1|install zendframework/zend-http 2.4.10|install zendframework/zend-http 2.4.11|install zendframework/zend-http 2.4.12|install zendframework/zend-http 2.4.13|install zendframework/zend-http 2.4.2|install zendframework/zend-http 2.4.3|install zendframework/zend-http 2.4.4|install zendframework/zend-http 2.4.5|install zendframework/zend-http 2.4.6|install zendframework/zend-http 2.4.7|install zendframework/zend-http 2.4.8|install zendframework/zend-http 2.4.9

**Comment by ibraheemnabeelfauzi** [comment]
Hello @nickpiro  please try the following command: `composer require laminas/laminas-http:2.10.0`
Thanks!

**Comment by ibraheemnabeelfauzi** [comment]
@nickpiro  what's the error? Please drop in a ticket at support@shipperhq.com with all relevant details.

**Comment by nickpiro** [comment]
@ibraheemnabeelfauzi 

500 responses when trying to synchronize with ShipperHQ, and the following entries appear to be associated:

[02-May-2022 20:11:54 UTC] PHP Fatal error:  Cannot declare class Zend_Http_Client_Adapter_Socket, because the name is already in use in /chroot/home/domain/domain.com/html/vendor/magento/zendframework1/library/Zend/Http/Client/Adapter/Socket.php on line 47
02/May/2022:16:11:53 -0400 GET domain.com /home/domain/domain.com/html/index.php pid:23983 took:0.494s mem:18mb cpu:58.69% status:500 {172.58.203.100}
172.58.203.100 172.58.203.100 - [02/May/2022:16:11:53 -0400] "GET /admin/shipperhq/synchronize/synchronize/ HTTP/1.1" 500 - "https://domain.com/admin/shipperhq/synchronize/" "Mozilla/5.0 (Macintosh;Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

**Comment by ibraheemnabeelfauzi** [comment]
@nickpiro 

What version of PHP/Magento, ShipperHQ extension are you running?

**Comment by nickpiro** [comment]
PHP 7.3.31
Magento 2.3.7
ShipperHQ 20.47.6
--


<br class="Apple-interchange-newline">

**Comment by ibraheemnabeelfauzi** [comment]
Thank you @nickpiro  

What changes were made prior to you seeing that error? Did you upgrade the extension or were there any other changes? 

Also, can you try to switch to PHP7.4 and perform the sync and see if you run into the same issue?

**Comment by nickpiro** [comment]
We're unable to switch to 7.4 on Magento 2.3.7 I believe because all of our modules to not fully work with that version. I can test it on our dev environment first.

No other changes other than the installation guideline you mentioned earlier in this ticket. 

We're running Redis, Varnish, we upgraded to 2.3.7 and upgraded SHQ along with it.

**Comment by ibraheemnabeelfauzi** [comment]
Thanks @nickpiro I strongly suggest doing so on dev as from looking at that exception it's likely caused by PHP incompatibility. Also, what other modules don't work on PHP 7.4?

**Comment by nickpiro** [comment]
So this version isn't compatible with 7.3?

**Comment by ibraheemnabeelfauzi** [comment]
For the most part yes, as we've made changes to ensure comptability with M2.4 and higher which works with 7.4 and up. What version of the extension were you on?

**Comment by nickpiro** [comment]
We were on a pretty old version. Apparently the sync resolved itself, because it's no longer happening. Our server company was updating HAproxy for us, we were on an old version. When they did that, something may have happened that fixed it? I'm not sure. But I'd say the sync is no longer an issue on our end.
