### ISSUE TITLE
Compatibility Issue with 2.4.4

### ISSUE THREAD

**Issue by zeeshan2523806** [shipperhq/module-shipper#114]
It seems the latest shipperhq module is not compatible with Magento 2.4.4 and is throwing composer warning when we tried to update it.

**Comment by n2diving-dgx** [comment]
$ php bin/magento --version
Magento CLI 2.4.4
$ php -v
PHP 8.1.4 (cli) (built: Apr 12 2022 11:12:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
$ composer require --update-no-dev shipperhq/module-shipper
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^20.47 for shipperhq/module-shipper
./composer.json has been updated
Running composer update shipperhq/module-shipper
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - shipperhq/library-graphql[20.2.0, ..., 20.3.0] require php ~7.1 -> your php version (8.1.4) does not satisfy that requirement.
    - shipperhq/module-shipper[20.47.0, ..., 20.47.6] require shipperhq/library-graphql ^20.2.0 -> satisfiable by shipperhq/library-graphql[20.2.0, 20.3.0].
    - Root composer.json requires shipperhq/module-shipper ^20.47 -> satisfiable by shipperhq/module-shipper[20.47.0, ..., 20.47.6].

Installation failed,

**Comment by xaecors** [comment]
Just to provide additional information, we ran into the following after attempting to upgrade to 2.4.4:

```
bin/magento setup:upgrade
PHP Fatal error:  Declaration of ShipperHQ\Logger\Model\Logger::debug($message, array $context = Array) must be compatible with Monolog\Logger::debug($message, array $context = Array): void in /{redacted}/vendor/shipperhq/module-logger/src/Model/Logger.php on line 84
```

**Comment by wsadasmit** [comment]
Hi @zeeshan2523806 and @n2diving-dgx , thanks for these submissions. We're reviewing the details and will update soon. Appreciate your raising this.

**Comment by zeeshan2523806** [comment]
@wsadasmit any estimation on when we would be able to release it ?

**Comment by wsadasmit** [comment]
Hi @zeeshan2523806 and @n2diving-dgx , can you please let me know if this is blocking you from running your live site, or if this is an issue with develop/staging environment only at this time? Thanks,

**Comment by zeeshan2523806** [comment]
@wsadasmit we are testing the upgrades on the dev only but this will ofcourse will be a serious blocker for all those merchant who are using shipperhq module and are plannning to go with the latest magento upgrade.

**Comment by n2diving-dgx** [comment]
Currently we are just qualifying our configuration with M2.4.4 on our .dev sites, with plans for migration to live production asap, hopefully by month end.  We current have about 5 extensions (out of a couple of dozen) that are blocking us, shipperhq being one of them.   Most had updated prior to release of M2.4.4 and the remainder generally seem to be updating extremely fast as the issue is usually fairly trivial, some untidy code that still contains a few bits of ancient deprecated php syntax.

**Comment by n2diving-dgx** [comment]
Is there an ETA on resolution of this issue, Shipper HQ is now the only extension blocking us from M2.4.4

**Comment by artursson** [comment]
Hi @n2diving-dgx 

I got the answer from ShipperHQ yesterday:

> The ETA we are looking at on this update is 2 weeks.

**Comment by wsajosh** [comment]
Thanks for your patience. We've released a new version which adds support for Magento 2.4.4 and PHP 8.1. Please go ahead and update
