### ISSUE TITLE
PHP 8.x Incompatibility with Calendar Module

### ISSUE THREAD

**Issue by Silarn** [shipperhq/module-shipper#116]
It wasn't clear to me where to report this since there doesn't seem to be a publicly accessible issue tracker.

The shipperhq/module-calendar package has an issue in Model/CalendarConfigProvider.php on line 115 as you can no longer pass a non-string value into strstr(). A null coalesce should fix it.

**Comment by WSAlewis** [comment]
Hello @Silarn,

Thanks for reaching out to us.

Currently, the Calendar module is not compatible with PHP 8.1, and Magento 2.4.4.

Our QA team is testing the latest unreleased update of this module which will provide support for the version mentioned above. We're expecting that this update to be available by the end of this week.

- Lewis, Technical Support Engineer at ShipperHQ

**Comment by n2diving-dgx** [comment]
Confirm issue with calendar module and PHP 8.1

This is causing shipperHQ to error out and can't see shipping options in shopping cart or anything at all when attempting to checkout.

[2022-05-24T16:17:04.278670+00:00] main.CRITICAL: Exception: Deprecated Functionality: strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/divegearexpress/www/releases/20220524151246/vendor/shipperhq/module-calendar/src/Model/CalendarConfigProvider.php on line 115 in /home/divegearexpress/www/releases/20220524151246/vendor/magento/framework/App/ErrorHandler.php:61

**Comment by wsajosh** [comment]
Hi,

Thanks for your patience. As of the end of May, all ShipperHQ modules are compatible with Magento 2.4.4 and PHP8.1.
