### ISSUE TITLE
Return type error in module-shipper during checkout 

### ISSUE THREAD

**Issue by n2diving-dgx** [shipperhq/module-shipper#117]
Magento 2.4.4  
ShipperHQ 20.48.1

main.CRITICAL: TypeError: Return value of ShipperHQ\Shipper\Helper\Data::isCheckout() must be of the type bool, null returned in /vendor/shipperhq/module-shipper/src/Helper/Data.php:290
Stack trace:
#0 /vendor/shipperhq/module-shipper/src/Model/Carrier/Shipper.php(355): ShipperHQ\Shipper\Helper\Data->isCheckout(Object(Magento\Quote\Model\Quote\Interceptor))
#1 /vendor/shipperhq/module-shipper/src/Model/Carrier/Shipper.php(315): ShipperHQ\Shipper\Model\Carrier\Shipper->setRequest(Object(Magento\Quote\Model\Quote\Address\RateRequest))
#2 /vendor/magento/module-shipping/Model/Shipping.php(335): ShipperHQ\Shipper\Model\Carrier\Shipper->collectRates(Object(Magento\Quote\Model\Quote\Address\RateRequest))
#3 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Shipping\Model\Shipping->collectCarrierRates('shqInStorePicku...', Object(Magento\Quote\Model\Quote\Address\RateRequest))
#4 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Shipping\Model\Shipping\Interceptor->___callParent('collectCarrierR...', Array)
#5 /vendor/shipperhq/module-shipper/src/Plugin/Shipping/ShippingPlugin.php(123): Magento\Shipping\Model\Shipping\Interceptor->Magento\Framework\Interception\{closure}('shqInStorePicku...', Object(Magento\Quote\Model\Quote\Address\RateRequest))
#6 /vendor/magento/framework/Interception/Interceptor.php(135): ShipperHQ\Shipper\Plugin\Shipping\ShippingPlugin->aroundCollectCarrierRates(Object(Magento\Shipping\Model\Shipping\Interceptor), Object(Closure), 'shqInStorePicku...', Object(Magento\Quote\Model\Quote\Address\RateRequest))
#7 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Shipping\Model\Shipping\Interceptor->Magento\Framework\Interception\{closure}('shqInStorePicku...', Object(Magento\Quote\Model\Quote\Address\RateRequest))
#8 /generated/code/Magento/Shipping/Model/Shipping/Interceptor.php(23): Magento\Shipping\Model\Shipping\Interceptor->___callPlugins('collectCarrierR...', Array, NULL)
#9 /vendor/magento/module-shipping/Model/Shipping.php(259): Magento\Shipping\Model\Shipping\Interceptor->collectCarrierRates('shqInStorePicku...', Object(Magento\Quote\Model\Quote\Address\RateRequest))
#10 /vendor/magento/module-quote/Model/Quote/Address.php(1077): Magento\Shipping\Model\Shipping->collectRates(Object(Magento\Quote\Model\Quote\Address\RateRequest))
#11 /vendor/magento/module-quote/Model/Quote/Address.php(1004): Magento\Quote\Model\Quote\Address->requestShippingRates()
#12 /vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php(83): Magento\Quote\Model\Quote\Address->collectShippingRates()
#13 /vendor/magento/module-quote/Model/Quote/TotalsCollector.php(261): Magento\Quote\Model\Quote\Address\Total\Shipping->collect(Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Quote\Model\ShippingAssignment), Object(Magento\Quote\Model\Quote\Address\Total))
#14 /vendor/magento/module-quote/Model/Quote/TotalsCollector.php(156): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals(Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Quote\Model\Quote\Address))
#15 /vendor/magento/module-quote/Model/Quote.php(2015): Magento\Quote\Model\Quote\TotalsCollector->collect(Object(Magento\Quote\Model\Quote\Interceptor))
#16 /vendor/magento/module-quote/Model/Quote/Payment.php(187): Magento\Quote\Model\Quote->collectTotals()
#17 /vendor/magento/module-quote/Model/PaymentMethodManagement.php(79): Magento\Quote\Model\Quote\Payment->importData(Object(Magento\Framework\DataObject))
#18 /vendor/magento/module-quote/Model/GuestCart/GuestPaymentMethodManagement.php(49): Magento\Quote\Model\PaymentMethodManagement->set('287693', Object(Magento\Quote\Model\Quote\Payment))
#19 /vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php(183): Magento\Quote\Model\GuestCart\GuestPaymentMethodManagement->set('gKEiOHQBfBXLloU...', Object(Magento\Quote\Model\Quote\Payment))
#20 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformation('gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#21 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#22 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#23 /generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(32): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#24 /vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php(122): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformation('gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#25 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#26 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#27 /vendor/rohitkundale/order-comment/Plugin/Model/Checkout/GuestPaymentInformationManagement.php(106): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#28 /vendor/magento/framework/Interception/Interceptor.php(135): RohitKundale\OrderComment\Plugin\Model\Checkout\GuestPaymentInformationManagement->aroundSavePaymentInformationAndPlaceOrder(Object(Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor), Object(Closure), 'gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#29 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#30 /generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, NULL)
#31 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder('gKEiOHQBfBXLloU...', 'bocaraffa@yahoo...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#32 /vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#33 /vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#34 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#36 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#38 /vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#40 /pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#41 {main} [] []

**Comment by ibraheemnabeelfauzi** [comment]
Hey @n2diving-dgx  please update to 20.48.2 which resolves this issue. 

Thank you.

**Comment by n2diving-dgx** [comment]
Thanks, 20.48.2 does resolve the issue.
