### ISSUE TITLE
Admin Shipping Page is Breaking in Magento 2.4.3-p1

### ISSUE THREAD

**Issue by TheRealHunzik** [shipperhq/module-shipper#119]
### Environment

Magento 2.4.3-p1
PHP 7.4
Module Version 20.49.0
All Inventory Related Modules Are Dsiabled

### Steps To Reproduce
Go tp Admin -> Order -> View Order -> Shipment -> View Shipment

### Expected Result:

Shipping Page Should Appear

### Actual Result:
 Error: Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface
#0 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#1 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#2 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#3 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#4 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#5 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#6 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#7 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#8 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#9 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#10 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#11 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#12 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#13 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#14 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#15 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#16 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#17 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#18 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#19 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#20 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#21 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#22 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#23 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#24 /home/eg-sol/www/tfs.local/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#25 /home/eg-sol/www/tfs.local/vendor/magento/module-shipping/Model/CarrierFactory.php(74): Magento\Framework\ObjectManager\ObjectManager->create()
#26 /home/eg-sol/www/tfs.local/vendor/magento/module-shipping/Model/Config.php(100): Magento\Shipping\Model\CarrierFactory->create()
#27 /home/eg-sol/www/tfs.local/vendor/magento/module-shipping/Block/Adminhtml/Order/Tracking.php(92): Magento\Shipping\Model\Config->getAllCarriers()

### Note:
I have debugged that and found that it is due to ShipperHQ_Shipping 
i have a disabled module to check and its working fine

**Comment by wsajosh** [comment]
Hi @TheRealHunzik The latest version of the extension should resolve this issue. Thanks for raising it.
