### ISSUE TITLE
Shipping Methods display errors on initial checkout page load

### ISSUE THREAD

**Issue by gorillagroup** [shipperhq/module-shipper#12]
On initial load of the checkout page, before any information has been entered, the Shipper HQ shipping methods are displayed with an error message and a $0.00 price.
Once the user enters a valid Shipping Address, the correct Shipping Methods and prices are loaded as expected. It appears this issue is caused by an estimate-shipping-methods ajax call firing at checkout load.

![checkout](https://cloud.githubusercontent.com/assets/14338522/19894594/f2fa67cc-a023-11e6-9003-adee1fc7da30.png)

**Comment by wsagen** [comment]
This is a native Magento 2 "feature" - it calls collectRates on all active shipping carriers when the checkout page is loaded. You can observe this by disabling ShipperHQ and enabling another core Magento live rate carrier e.g. UPS - rates are requested when checkout page loads. 

In ShipperHQ we have included a configuration setting on the shipping method configuration page to "require zip code" before requesting shipping rates. This will prevent this initial shipping method error display.
