### ISSUE TITLE
StockHandlerFactory check for Inventory module usage fails if module is installed and disabled

### ISSUE THREAD

**Issue by steven-hoffman-jomashop** [shipperhq/module-shipper#122]
For https://github.com/shipperhq/module-shipper/blob/20.50.0/src/Model/Carrier/Processor/StockHandlerFactory.php.
The [isAdobeMSIInstalled](https://github.com/shipperhq/module-shipper/blob/20.50.0/src/Model/Carrier/Processor/StockHandlerFactory.php#L60) and [isLegacyStockRegistryInstalled](https://github.com/shipperhq/module-shipper/blob/20.50.0/src/Model/Carrier/Processor/StockHandlerFactory.php#L68) can return incorrect results if the module is installed and disabled.

This can be easily fixed by adding a Magento\Framework\Module\Manager::isEnabled check on the relevant modules. (Magento_InventoryCatalog & Magento_CatalogInventory)

**Comment by wsajosh** [comment]
@steven-hoffman-jomashop Thanks for raising this. We've released version 20.50.1 which addresses this. Please update and re-test
