### ISSUE TITLE
ShipperHQ Calendar Date Picker not working in admin

### ISSUE THREAD

**Issue by dangtrinhtran** [shipperhq/module-shipper#125]
Hello,

I'm using:
- Magento CE 2.4.4 and PHP 8.1
- shipperhq/module-shipper: 20.50.1
- shipperhq/module-calendar: 22.8.0

My issue is to place orders via the admin and the date picker reverts back to min_date after I enter the date that the customer wants.
<img width="2379" alt="Screen Shot 2022-11-03 at 5 29 23 PM" src="https://user-images.githubusercontent.com/3252322/199838049-05cc51bc-4ba9-44f0-825c-6f551399f6a4.png">

For example: After I select 11/30/2022, the Delivery Date always reverts back to min_date which is 11/08/2022.

Can someone help me?

**Comment by wsadaniel** [comment]
Hi @mrRonyTran, we're looking into this but would you be able to email in to support @ shipperhq.com and let us know what ShipperHQ account you're connected to when seeing this issue?

Also, worth noting that the current version of shipperhq/module-shipper is 20.51.3 so please update and retest with the current version and let us know if you're able to reproduce there.

**Comment by mrRonyTran** [comment]
Hi @wsadaniel 

I have updated shipperhq/module-shipper to the latest version 20.51.3 and the issue still happens. I'm going to send an email right now.

Thanks.

**Comment by wsadaniel** [comment]
Thanks @mrRonyTran, we've attempted to reproduce on our side but have not been able to. Will provide further feedback once we have that info from you.

**Comment by mrRonyTran** [comment]
@wsadaniel I just sent my ShipperHQ account through email.
