### ISSUE TITLE
Integrity constraint violation while upgrade the site

### ISSUE THREAD

**Issue by nikilmethew** [shipperhq/module-shipper#126]
Unable to apply data patch ShipperHQ\Shipper\Setup\Patch\Data\InstallCoreProductAttributes for module ShipperHQ_Shipper.

We upgrade the site 2.3.7 to 2.4.4, 
PHP 8.1.10
shipperhq/module-shipper: [20.51.3]

While run the upgrade command the error is coming
Unable to apply data patch ShipperHQ\Shipper\Setup\Patch\Data\InstallCoreProductAttributes for module ShipperHQ_Shipper.
![image](https://user-images.githubusercontent.com/46815046/201675202-cbe79764-3142-4261-a91a-aa791e8aeac0.png)

**Comment by WSAlewis** [comment]
Hello @nikilmethew, thanks for reaching out to us.

I've gone ahead and raised this to our development team for further review. 

Whilst this is under review by our team, would you be able to confirm that you followed these update steps here:
https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/#Updating_Existing_Installation

Either myself or another member of the team will reach out with an update.

Lewis
ShipperHQ Support Engineer

**Comment by WSAlewis** [comment]
Hello @nikilmethew, just following up on this.

Our development team have also confirm that we'll need to know the command that you used for updating this module.

Once we have this information, we'll be able to assist further.

Lewis
ShipperHQ Support Engineer

**Comment by WSAlewis** [comment]
Hello @nikilmethew,

This thread will now close due to inactivity.

Should you have any issues or concerns feel free to reach out to us here or at support@shipperhq.com and we'll be happy to assist you further.

Lewis
ShipperHQ Support Engineer
