### ISSUE TITLE
Incorrect data type provided for freight_class attribute

### ISSUE THREAD

**Issue by xaevik** [shipperhq/module-shipper#127]
We began experiencing an issue with order exports failing due to an implicit cast conversion deprecation being thrown. Upon investigation it was revealed that `freight_class` has an incorrect data type defined:

https://github.com/shipperhq/module-shipper/blob/321086b52e73302b1ec12dfd45b4d80532c4bdbd/src/Setup/Patch/Data/InstallFreightAttributes.php#L77-L78

It should be `decimal` not `int` as there are numerous freight classes (e.g., 77.5) that cannot be treated as integers.

Edit: `string` might be a better option if a numeric primitive is not really needed.

We have patched our environments in the interim until this issue is fixed in upstream.

**Comment by wsajosh** [comment]
Hi @xaevik 

Thanks for raising this. I've just released a new version of the extension which corrects this issue. Please update when you can.
