### ISSUE TITLE
First address entered during checkout is not saved to address book

### ISSUE THREAD

**Issue by gorillagroup** [shipperhq/module-shipper#13]
When the module ShipperHQ_Shipper is disabled this issue is no longer happening.
\ShipperHQ\Shipper\Plugin\Checkout\ShippingInformationPlugin is doing some things in aroundSaveAddressInformation and it seems to be causing this. I think this event "around" might not be the right one since \Magento\Checkout\Model\ShippingInformationManagement::saveAddressInformation is being called after.

**Steps to reproduce:**
1. Register a new user.
2. Complete checkout using physical product.
3. Start checkout with another physical product in cart.
**Expected result:**
Address used on step two is saved as default shipping address and can be used on step three.
**Actual result:**
User has to enter new address from scratch.

**Comment by wsagen** [comment]
Can you confirm the Magento version you are using? We are not seeing this issue after repeated attempts to reproduce

**Comment by gorillagroup** [comment]
This project is on 2.1.2.

**Comment by wsagen** [comment]
Reviewed with GorillaGroup and found it was unrelated to ShipperHQ. Closing
