### ISSUE TITLE
ShipperHQ is not compatible with Magneto 2.4.6 

### ISSUE THREAD

**Issue by n2diving-dgx** [shipperhq/module-shipper#130]
Compatibility issue with ShipperHQ and Magento 2.4.6 released March 2023.  ShipperHQ doesn't return rates in cart, attempting checkout throws exception, attempting to refresh token fails. ShipperHQ functions as normal on M2.4.5-p2 and earlier.  Error logged in system.log starts out like this....  

[2023-03-16T01:18:43.502544+00:00] main.CRITICAL: Error: Class "Zend_Http_Client" not found in /home/www/releases/vendor/shipperhq/library-ws/src/Client/WebServiceClient.php:48
Stack trace:
#0 /home/www/releases/vendor/shipperhq/**module-shipper**/src/Model/Carrier/Shipper.php(467): ShipperHQ\WS\Client\WebServiceClient->sendAndReceive()
#1 /home/www/releases/vendor/shipperhq/module-shipper/src/Model/Carrier/Shipper.php(322): ShipperHQ\Shipper\Model\Carrier\Shipper->getQuotes()
#2 /home/www/releases/vendor/magento/module-shipping/Model/Shipping.php(335): ShipperHQ\Shipper\Model\Carrier\Shipper->collectRates()
#3 /home/www/releases/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Shipping\Model\Shipping->collectCarrierRates()
#4 /home/www/releases/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Shipping\Model\Shipping\Interceptor->___callParent()
#5 /home/www/releases/vendor/shipperhq/module-shipper/src/Plugin/Shipping/ShippingPlugin.php(123): Magento\Shipping\Model\Shipping\Interceptor->Magento\Framework\Interception\{closure}()

**Comment by WSAlewis** [comment]
Hello @n2diving-dgx,

We have released a fix within the latest version of our modules. You can update with dependencies to install this fix by following our steps outlined here:

https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/#Updating_Existing_Installation

Let us know if you run into any issues.

Lewis Kennedy - ShipperHQ Support
