### ISSUE TITLE
Admin Product Edit - Shipping Group record is not removed when use default is selected & saved

### ISSUE THREAD

**Issue by gene-roussetos** [shipperhq/module-shipper#132]
Hi, this is more to confirm behaviour on this.

Our client is on Magento `2.4.5-p1` & uses `20.51.6` version of the ShipperHQ module.

1. A product has a specific `Shipping Group` selected in the `All Store Views` scope & the same group only selected in a store scope.
2. On the store level, If we check the `Use Default` option & click save the Product, the database entry is not removed but instead it is set to null.

Is this expected behaviour? is there a chance this is an issue with the module in the sense of how the attribute is created?
It does feel more like a Magento/Application issue, but thought of asking

Thank you!

<img width="633" alt="Screenshot 2023-03-24 at 17 15 21" src="https://user-images.githubusercontent.com/84732055/227597587-a62a7422-ae6d-44c6-b35f-8f3ed5fd229e.png">

**Comment by gene-roussetos** [comment]
@WSAlewis thank you for your reply.

Just to confirm, this is the `catalog_product_entity_text` table we are referencing

`attribute_id` 743 is the `Shipping Group` attribute as shown below (referencing `eav_attribute` db table)
<img width="1371" alt="Screenshot 2023-03-27 at 11 53 49" src="https://user-images.githubusercontent.com/84732055/227922011-66ac13ab-091a-497c-9453-65d8a7712339.png">



More or less, we
1. Expect to have an additional row in the table if a shipping group is selected on store view (value being the same as the All store views)
2. Expect the additional record (for store view) to be removed once the `Use Default` is checked.

**Comment by WSAlewis** [comment]
Thanks for the quick response @gene-roussetos,

I'll pass this feedback across to our team.

Let me know if the status of the issue changes.

**Comment by gene-roussetos** [comment]
@WSAlewis picked this up again after ages.
Magento core bug after all. Commerce module with plugin that sets an empty value on multiselect attributes if value is `== null`

Quality Patch available
[ACSD-49835](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-29/acsd-49835-use-default-value-chekbox-not-saved.html?lang=en)
```
Fixes the issue where the Use default checkbox value is not saved correctly on a store level for a multi-select attribute.
```

**Comment by WSAlewis** [comment]
Hello @gene-roussetos I appreciate you following up here!

Glad to hear that the cause was located and resolved on Magento's side. Should you run into any other issues let us know and we'll investigate further.

Thanks again!

Lewis Kennedy - ShipperHQ Support
