### ISSUE TITLE
«UPS Shipping - undefined» message in order total block in shopping cart is not rates are available

### ISSUE THREAD

**Issue by gorillagroup** [shipperhq/module-shipper#14]
This seems to be related to issue #12. The estimate-shipping-methods call combined with the shipperhq module doesn't seem to handle bad or missing address data well.

**Steps to reproduce:**
Estimate shipping and tax using wrong state/ZIP combination.
**Expected result:**
Zero dollar shipping doesn't appear in Order Total block as shipping is not available
**Actual result:**
Free «UPS Shipping - undefined» shipping appears in Order Total.

![croppercapture 339](https://cloud.githubusercontent.com/assets/14338522/19929385/75af2544-a0d9-11e6-9466-de45d128ad5a.png)

**Comment by wsagen** [comment]
This appears to be a Magento issue. I've reproduced using core Magento UPS carrier enabled and all other shipping methods disabled (including ShipperHQ). 
Could you please raise with Magento development team or enterprise support
