### ISSUE TITLE
Why save shipping address during the estimate-shipping-methods api call?

### ISSUE THREAD

**Issue by gorillagroup** [shipperhq/module-shipper#17]
Recently we've had an intermittent issue when the **shipping_method** was not set to Shipping address correctly after Shipping step. It seems there was a single use-case where `estimate-shipping-methods` and `shipping-information` concurrent api calls aligned in a way that Shipping address saved in \ShipperHQ\Shipper\Plugin\Quote\ShippingMethodManagementPlugin::saveShippingAddress was overwriting the one with shipping_method assigned.

The question is: why are you saving shipping address during the estimation (that clearly is not done in Magento by design)?

**Comment by wsagen** [comment]
Thanks for raising. 

We implemented this as a work around for several Magento issues early on, where they were not passing address fields when requesting shipping rates in some circumstances. 

We can see potential for issue here and are investigating alternatives.

**Comment by wsagen** [comment]
Thanks for raising issue with us. We've refactored some of our logic to exclude this plugin from standard ShipperHQ rate requests. If you update to the latest version this issue is resolved.
