### ISSUE TITLE
Multi-website: Exception: No such entity with cartId = ...

### ISSUE THREAD

**Issue by alexpoletaev** [shipperhq/module-shipper#19]
### Preconditions
1. Multi-website Magento instance

### Steps to reproduce
1. Create an order from the admin panel, but NOT for the default store 

### Expected result
1. An order placed successfully

### Actual result
1. The **No such entity with cartId = ...** error occurs

### Possible fix
Find this method ```\ShipperHQ\Shipper\Observer\RecordAdminOrder::execute()``` and set the current store before recording the order (do not forget to inject the StoreManagerInterface to the constructor):
```
public function execute(EventObserver $observer)
    {
        if ($this->shipperDataHelper->getConfigValue('carriers/shipper/active')) {
            $order = $observer->getEvent()->getData('order');
            $this->storeManager->setCurrentStore($order->getStoreId());
            if($order->getIncrementId()) {
                $this->recordOrder($order);
            }
        }
    }
```

Look at this https://github.com/magento/magento2/issues/6522 core bug for more info.

**Comment by wsagen** [comment]
Thanks for raising - this is clearly a Magento core issue but we are reviewing to see if we can implement a work around

**Comment by vkalchenko** [comment]
Hi, we have exactly the same issue with Multi-website and admin orders for non-default store.  As a workaround, I think passing store_id of the order should be more less safe...
See pull request https://github.com/shipperhq/module-shipper/pull/20

**Comment by wsagen** [comment]
Thanks for your contribution. We appreciate the pull request, our internal process means that changes are not pushed directly to this repository. However we've implemented your pull request in full @vkalchenko and have credited you in the code. 
Latest release includes this fix so I am closing the issue.
