### ISSUE TITLE
All SetupUpgrade runs every time a new setup version is discovered

### ISSUE THREAD

**Issue by daniel-ifrim** [shipperhq/module-shipper#23]
SetupUpgrade.php should have version_compare() if statements by module's setup version.
I see SetupSchema has version_compare, but not SetupUpgrade doesn't.

If I have 1.0.9 and I just upgraded to 1.0.10, all instructions are run.
Although addAttribute and other functions from $categorySetup/Factory are fail safe, it's still not proper to run those functions.

**Comment by wsagen** [comment]
Thanks for raising, we've modified the upgrade scripts to include version checks in latest and all future versions.
