### ISSUE TITLE
Module breaks DI compilation

### ISSUE THREAD

**Issue by sshymko** [shipperhq/module-shipper#25]
**Environment:**
- Magento CE 2.1.x
- ShipperHQ module v20.5.4

**Steps to reproduce:**
1. Install vanilla Magento 2 via Composer
2. Install the ShipperHQ module via Composer
3. Run code generation and DI compilation:
```
php bin/magento setup:di:compile
```

**Actual result:**
- DI compilation fails with the following error:
```
  [ReflectionException]                                                                                     
  Class ShipperHQ\Common\Model\Quote\Service does not exist  
```
- Constructor of the class `\ShipperHQ\Shipper\Observer\SaveShippingAdmin` declares dependency on non-existing class `\ShipperHQ\Common\Model\Quote\Service`

**Comment by wsagen** [comment]
Can you please verify the version of shipperhq/module-common you have. The current version can be seen in vendor/shipperhq/module-common/CHANGELOG.MD file. 

The most recent version of 20.1.5 which includes the class ShipperHQ\Common\Model\Quote\Service at vendor/shipperhq/module-common/src/Model/Quote/Service.php

Can you verify the above version number and that the file is present. Please update the installation and retest if you version is lower that the above.

**Comment by sshymko** [comment]
@wsagen 
The changelog `vendor/shipperhq/module-common/CHANGELOG.MD` shows 20.1.2 (2016-12-14).

**Comment by sshymko** [comment]
Full upgrading the module with all dependencies resolved the issue. Closing.
