### ISSUE TITLE
Credentials decryption

### ISSUE THREAD

**Issue by johnekj** [shipperhq/module-shipper#31]
I installed ShipperHQ on Magento 2. My installed version is 20.6.0. I was trying to configure it, but it says "ShipperHQ Error: Invalid Credentials. The credentials you supplied are invalid." My credentials were ok, so I xdebugged it and I saw, that credentials are not decrypted before using them for contacting with ShipperHQ server. In db they are stored as encrypted, but they are not decrypted before use.
Am I doing something wrong or you need to fix it? Please check it.

**Comment by wsagen** [comment]
Please also ensure you have refreshed your cache by removing the contents of var/cache directory and then try to resave your credentials. 
If that doesn't resolve the issue, there's a known issue with PHP 7 and encrypted fields, that may be causing this

https://github.com/magento/magento2/issues/2984
