### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 4 passed to ShipperHQ\Shipper\Ui\Component\Listing\Column\DeliveryDate

### ISSUE THREAD

**Issue by ramshankar5july** [shipperhq/module-shipper#39]
Fatal error: Uncaught TypeError: Argument 4 passed to Magento\Ui\Component\Listing\Columns\Date::__construct() must be an instance of Magento\Framework\Stdlib\BooleanUtils, array given, called in /public_html/app/code/ShipperHQ/Shipper/Ui/Component/Listing/Column/DeliveryDate.php on line 68 and defined in /public_html/vendor/magento/module-ui/Component/Listing/Columns/Date.php:37 Stack trace: #0 /public_html/app/code/ShipperHQ/Shipper/Ui/Component/Listing/Column/DeliveryDate.php(68): Magento\Ui\Component\Listing\Columns\Date->__construct(Object(Magento\Framework\View\Element\UiComponent\Context), Object(Magento\Framework\View\Element\UiComponentFactory), Object(Magento\Framework\Stdlib\DateTime\Timezone), Array, Array) #1 /public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): ShipperHQ\Shipper\Ui\Component\Listing\Column\DeliveryDate->__construct(Object(Magento\Framework\View\Element\UiComponent\Context), Obj in /public_html/vendor/magento/module-ui/Component/Listing/Columns/Date.php on line 37

**Comment by ramshankar5july** [comment]
I've upgraded magento version (Magento 2.1.8 to Magento 2.2.2) using admin setup tool. When I login and click on  sales -> order menu I got above error. and also checkout is not working.

**Comment by wsajason** [comment]
Hi. If you have not done so already we recommend updating to the latest version of the extension, which should resolve this.
[This article](http://docs.shipperhq.com/installing-magento-2-shipperhq-extension/) covers how to update the extension.

**Comment by ramshankar5july** [comment]
Hi wsajason ,
Thanks,
I am using below steps. and above problem is solved.
Clean Install
Run the following commands from your root Magento installation directory:
composer require shipperhq/module-shipper
composer require shipperhq/module-logger
composer update shipperhq/*
php bin/magento setup:upgrade
Flush & Re-enable the cache if required
Remove generated file content by deleting contents of:
var/view_preprocessed
pub/static/frontend/ 
pub/static/_requirejs/
pub/static/adminhtml/
var/generation
var/cache
var/page_cache
If you are in default or production mode, you will need to recompile your code bin/magento setup:di:compile

**Comment by wsajosh** [comment]
Thanks for letting us know that the issue was solved by the above steps.
