### ISSUE TITLE
Errors During Compilation

### ISSUE THREAD

**Issue by pioneerathletics** [shipperhq/module-shipper#40]
Hi,

I tried updating to the latest ShipperHQ version and received a few errors during compilation.

### Preconditions

1. Magento 2.1.10
2. PHP 7

### Steps to reproduce

1. Updated to ShipperHQ-20.14.0 via composer using composer update shipperhq/*
2. bin/magento setup:upgrade
3. bin/magento setup:di:compile

### Expected result

1. ShipperHQ should update with no errors

### Actual result

1. ShipperHQ updated but with the following errors during compilation:
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxx/xxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1
Errors during compilation:
	ShipperHQ\Shipper\Helper\Module
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Module in /home/xxxxx/xxxxx/vendor/shipperhq/module-shipper/src/Helper/Module.php
\Magento\Framework\Module\Manager already exists in context object
Total Errors Count: 1

**Comment by wsajosh** [comment]
Hi, thanks for raising this issue! We've just released a update (20.14.1) which addresses this
