### ISSUE TITLE
Error at checkout - Magento Enterprise 2.2.3 

### ISSUE THREAD

**Issue by julienha** [shipperhq/module-shipper#41]
Hi,

I updated Magento to : 
Magento EE => 2.2.3
Shipper module (shipperhq/module-shipper) => 20.15.0

A http 500 error occurs at the checkout, right after clicking the "Next" button. 
A shipping address, and a shipping method have been selected just before this action.

**Error :** 
Warning: array_merge(): Argument #1 is not an array in /var/www/dev.marsmarket.be/vendor/shipperhq/module-shipper/src/Plugin/Checkout/ShippingInformationPlugin.php on line 166

**Stack :** [stack_trace.txt](https://github.com/shipperhq/module-shipper/files/1824815/stack_trace.txt)

**Comment by julienha** [comment]
The checkout process is working fine if the module is disabled via bin/magento disable:module ShipperHQ_Shipper

**Comment by wsagen** [comment]
Thanks for reporting, we are currently investigating and should have a fix for you shortly

**Comment by wsagen** [comment]
Thanks again for raising this issue @julienha, the latest release (v20.15.1) will resolve this error
