### ISSUE TITLE
How to include Estimated Delivery Dates when getting shipping rates?

### ISSUE THREAD

**Issue by loganstellway** [shipperhq/module-shipper#42]
I see that ShipperHQ promotes the ability to [estimate delivery dates / shipping times](http://docs.shipperhq.com/shipperhq-date-and-time-capabilities/).

I am exploring the modules to find how to get this data when requesting quotes. 
>ShipperHQ\Shipper\Model\Carrier\Shipper::getQuotes()

I see a few lines checking for a `delivery_date` field from the returned rate data in the following method:
>ShipperHQ\Shipper\Model\Carrier\Shipper::parseShipperResponse()

Would you be able to provide any guidance for providing an estimated delivery date? 

Thank you.

**Comment by wsaanthony** [comment]
Hello Logan,

ShipperHQ saves additional information for each order in custom columns on the order table and order items table.

You can access these values using direct calls e.g. $order->getData("delivery_date") or by using the order API to extract what you need. See this article below for usage and further explanation. 

http://docs.shipperhq.com/integrating-shipperhq-with-your-order-management-or-fulfilment-service/

Rgds,
Anthony Walker

**Comment by loganstellway** [comment]
For the record, I needed to enable the **Date & Time** feature under **Account Settings > Features**.
