### ISSUE TITLE
Different address types return "cached" rates in checkout

### ISSUE THREAD

**Issue by loganstellway** [shipperhq/module-shipper#43]
I am testing our checkout with a new rate configuration. We have updated our rates for shipping to locations outside of the US 48. We have different charges for both Residential and Business addresses. 

1. On the first try after loading an address, (with cookies and caches cleared), I get the correct rates. 
2. After changing the address (even after refreshing the checkout page), the old rates are returned.

**Notes**

- Both addresses are in the same city (Kihei, Hawaii)
  - They both have the same zip code.
  - One is **Business**, and the other is **Residential**
- I temporarily passed a blank array for the `options` argument of `selectedOptionsFactory` in:
`ShipperHQ\Shipper\Model\Carrier\Processor\ShipperMapper::getSelectedOptions()`
  - Explanation: I noticed a `destination_type` was created and passed in the request and wanted to make sure the option was not cached between requests
- I also tried returning false in `ShipperHQ\Shipper\Helper\CarrierCache::getCachedQuotes()` to ensure that there were no cached requests

Do you have any idea what could be happening here? 

Thank you

**Comment by wsajason** [comment]
Hi,

The most likely cause for this would not be a part of the module.

If you [email us](mailto:support@shipperhq.com) a transaction ID for these scenarios we can investigate to ensure that the address type is being determined for each request: http://docs.shipperhq.com/how-to-find-transaction-id-in-magento-2/
