### ISSUE TITLE
Simple products not treated independently from their configurable products

### ISSUE THREAD

**Issue by RBotfield** [shipperhq/module-shipper#45]
I'm currently seeing a bug in which the shipping group of the child product in a configurable is not being recognised. The simple products in this scenario need to have different shipping groups as they're different weights and sizes. 

When I add a simple product that is a child of a configurable, only the configurable's shipping group is used, though if I add the simple product directly, the shipping group is fine. 

Details:
- shipping group "sample" is set to have shipping price 3.95 in Shipper HQ
- undefined shipping groups are set to have shipping price 6.95 in ShipperHQ
- product "C" has an undefined shipping group, and is a configurable product in Magento
- product "S" is in shipping group "sample" and is a simple product, which is also a child of product "C" in Magento
- adding "S" to the basket directly gives me shipping price 3.95 on the checkout (expected) 
- adding "S" as a child product of "C" gives price 6.95 on the checkout (erroneous) 

I'm running Magento 2.1.12 with version 20.18.8 of this module.

Any help would be greatly appreciated!

**Comment by wsaDemo** [comment]
-- Please reply above this line --


Hey there,

Are you able to provide me the url of which website you are working
with. I would also make sure that you have the configuration set up
correctly for using child product attributes. You will want to have
"Use Parent" DESELECTED from within the website configuration, in
order to pick up the correct values.

If you have already done so, then we would need a transaction id [1]
to see if the information is being passed over properly in the
request.

Links:
------
[1] http://docs.shipperhq.com/how-to-find-transaction-id-in-magento-2/

 Regards, 

 Alec 
   [1]   SHIPPERHQ  | support@shipperhq.com [2]
US +1 (512) 215-4282 | UK +44 (0)1722-446240
 [3]  [4]

All of our WebShopApps extensions are now available as part
of ShipperHQ [5] on all major ecommerce platforms. Learn how you
can migrate for free [6]!

How would you rate my reply?
Great [7]    Okay [8]    Not Good [9]


Links:
------
[1] http://www.ShipperHQ.com
[2] mailto:support@shipperhq.com
[3] http://www.twitter.com/shipperhq
[4] http://www.facebook.com/shipperhq
[5] http://shipperhq.com/
[6] http://webshopapps.com/us/migration/
[7]
https://secure.helpscout.net/satisfaction/184909651/record/1605974958/1/
[8]
https://secure.helpscout.net/satisfaction/184909651/record/1605974958/2/
[9]
https://secure.helpscout.net/satisfaction/184909651/record/1605974958/3/
