### ISSUE TITLE
20.18.0 SHQ18-112 Introduced a potential issue with joins in 2.2.4+

### ISSUE THREAD

**Issue by Silarn** [shipperhq/module-shipper#46]
In Magento 2.2.4, the Amazon module is now an integrated part of Magento. This causes a conflict with the Helper\CarrierGroup function 'getQuoteShippingAddressFromOrder' because it uses the field 'entity_id' as a filter.

However, the Amazon modules do automatic extension_attributes joins on this table which includes another entity_id column. This causes failures with the joins due to the SQL not specifying the table.

You should be able to avoid this by specifying 'main_table.entity_id' in your filter.

**Comment by wsajosh** [comment]
Hey @Silarn Thanks for raising this! We're aware of this issue and working on a fix. We will be releasing a update to address this shortly
