### ISSUE TITLE
Orders grid "join"

### ISSUE THREAD

**Issue by yrudiuk** [shipperhq/module-shipper#48]
Hello,

We are using SHQ 20.3.2 version and have a question.
\ShipperHQ\Shipper\Plugin\Order\CollectionFactory::aroundGetReport adds "join left" into main order grid query but does not use any data from joined table.
Is there a reason for this?

Query becomes heavy with this "join" for us.

Thanks!

**Comment by wsajosh** [comment]
Hi @yrudiuk 

Thanks for getting in touch. This join is required. The result is passed back to Magento which will include ShipperHQ data and the original order data. Magento will then render that result.
