### ISSUE TITLE
Dimensional box value not saved in sales_order table?

### ISSUE THREAD

**Issue by EzzyEcom** [shipperhq/module-shipper#49]
ShipperHQ is not saving the Dimensional box in Magento 2 sales_order db table.
 
Can we get the module to the box for the shipment in the sales_order table?

**Comment by EzzyEcom** [comment]
Also why is the `getPackageBreakdownText` saving and adding comment to each order detail multiple times when on M1 `webshopapps` does it once?

**Comment by EzzyEcom** [comment]
![image](https://user-images.githubusercontent.com/6163189/43294071-96e3d3c6-910b-11e8-95c9-99f97e42ebc1.png)

![image](https://user-images.githubusercontent.com/6163189/43294095-b49d35c4-910b-11e8-81ab-eed40868ba09.png)

**Comment by EzzyEcom** [comment]
The perpetrator in question could be this on line vendor/vaprzonm2/shipperhq_module-shipper/src/Observer/BeforeSaveOrderShipment.php:99 of the ```function execute(EventObserver $observer)```

**Comment by wsajosh** [comment]
Hi @EzzyEcom 

We don't save to sales_order, we save to our own table called shipperhq_order_packages. This is in line with Magento guidelines.

It will save each packed box into that table. There could be multiple packed boxes per order or just one. The order you've screen shot has 26 boxes so I'd expect to see 26 entries in that table for the order. We used a similar mechanism in WebShopApps dimensional shipping in later versions.
