### ISSUE TITLE
di:compile Issues

### ISSUE THREAD

**Issue by jksimoniii** [shipperhq/module-shipper#5]
Running setup:di:compile throws the following errors although the compilation never actually fails. I haven't been able to identify a fix yet, but will report back if I find something.

```
ShipperHQ\Shipper\Helper\Data
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Data in app/code/ShipperHQ/Shipper/Helper/Data.php \Magento\Framework\App\Config\ScopeConfigInterface already exists in context object


```

**Comment by wsagen** [comment]
Thanks for highlighting although I'm not able to reproduce this locally. 

Have you done a composer update ? 
Are you using the standard or multi-tenant compile command?

**Comment by wsagen** [comment]
Closing as not able to reproduce
