### ISSUE TITLE
ShipperHQ Address Auto Complete causing error after removal

### ISSUE THREAD

**Issue by chattertech** [shipperhq/module-shipper#51]
Magento V2.23

ShipperHQ Address AutoComplete V20.1.3

I installed ShipperHQ Address Autocomplete via marketplace.

I ended up not needing it. I removed it with Extension Manager.

When i try and create New Orders i get the following error in Production Mode.

Class ShipperHQ\Shipper\Model\Customer\Attribute\Source\AddressType does not exist

In Developer mode i get the following error after clicking New Order.

1 exception(s):
Exception #0 (ReflectionException): Class ShipperHQ\Shipper\Model\Customer\Attribute\Source\AddressType does not exist

Exception #0 (ReflectionException): Class ShipperHQ\Shipper\Model\Customer\Attribute\Source\AddressType does not exist
#0 /home/pond/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('ShipperHQ\\Shipp...')
#1 /home/pond/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('ShipperHQ\\Shipp...')
#2 /home/pond/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('ShipperHQ\\Shipp...')
#3 /home/pond/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('ShipperHQ\\Shipp...', Array)
#4 /home/pond/public_html/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('ShipperHQ\\Shipp...', Array)
#5 /home/pond/public_html/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(590): Magento\Framework\Validator\UniversalFactory->create('ShipperHQ\\Shipp...')
#6 /home/pond/public_html/vendor/magento/module-customer/Model/AttributeMetadataConverter.php(68): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource()
#7 /home/pond/public_html/vendor/magento/module-customer/Model/Metadata/AddressMetadata.php(60): Magento\Customer\Model\AttributeMetadataConverter->createMetadataAttribute(Object(Magento\Customer\Model\Attribute))
#8 /home/pond/public_html/vendor/magento/module-customer/Model/Metadata/CachedMetadata.php(57): Magento\Customer\Model\Metadata\AddressMetadata->getAttributes('adminhtml_custo...')
#9 /home/pond/public_html/vendor/magento/module-customer/Model/Metadata/Form.php(152): Magento\Customer\Model\Metadata\CachedMetadata->getAttributes('adminhtml_custo...')
#10 /home/pond/public_html/vendor/magento/module-sales/Block/Adminhtml/Order/Create/Form/Address.php(223): Magento\Customer\Model\Metadata\Form->getAttributes()
#11 /home/pond/public_html/vendor/magento/module-sales/Block/Adminhtml/Order/Create/Billing/Address.php(46): Magento\Sales\Block\Adminhtml\Order\Create\Form\Address->_prepareForm()
#12 /home/pond/public_html/vendor/magento/module-sales/Block/Adminhtml/Order/Create/Form/AbstractForm.php(101): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address->_prepareForm()
#13 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Billing/Address/Interceptor.php(141): Magento\Sales\Block\Adminhtml\Order\Create\Form\AbstractForm->getForm()
#14 /home/pond/public_html/vendor/magento/module-sales/view/adminhtml/templates/order/create/form/address.phtml(55): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->getForm()
#15 /home/pond/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/pond/publ...')
#16 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor), '/home/pond/publ...', Array)
#17 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\Template->fetchView('/home/pond/publ...')
#18 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->___callParent('fetchView', Array)
#19 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->Magento\Framework\Interception\{closure}('/home/pond/publ...')
#20 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Billing/Address/Interceptor.php(468): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->___callPlugins('fetchView', Array, Array)
#21 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->fetchView('/home/pond/publ...')
#22 /home/pond/public_html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#23 /home/pond/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#24 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Billing/Address/Interceptor.php(791): Magento\Framework\View\Element\AbstractBlock->toHtml()
#25 /home/pond/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->toHtml()
#26 /home/pond/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('billing_address')
#27 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('billing_address')
#28 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('billing_address')
#29 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('billing_address', true)
#30 /home/pond/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('billing_address', true)
#31 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Data/Interceptor.php(622): Magento\Framework\View\Element\AbstractBlock->getChildHtml('billing_address', true)
#32 /home/pond/public_html/vendor/magento/module-sales/view/adminhtml/templates/order/create/data.phtml(42): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->getChildHtml('billing_address')
#33 /home/pond/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/pond/publ...')
#34 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor), '/home/pond/publ...', Array)
#35 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\Template->fetchView('/home/pond/publ...')
#36 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->___callParent('fetchView', Array)
#37 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->Magento\Framework\Interception\{closure}('/home/pond/publ...')
#38 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Data/Interceptor.php(390): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->___callPlugins('fetchView', Array, Array)
#39 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->fetchView('/home/pond/publ...')
#40 /home/pond/public_html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#41 /home/pond/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#42 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Data/Interceptor.php(713): Magento\Framework\View\Element\AbstractBlock->toHtml()
#43 /home/pond/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->toHtml()
#44 /home/pond/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('data')
#45 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('data')
#46 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('data')
#47 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('data', true)
#48 /home/pond/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('data', true)
#49 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Form/Interceptor.php(648): Magento\Framework\View\Element\AbstractBlock->getChildHtml('data', true)
#50 /home/pond/public_html/vendor/magento/module-sales/view/adminhtml/templates/order/create/form.phtml(23): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->getChildHtml('data')
#51 /home/pond/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/pond/publ...')
#52 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor), '/home/pond/publ...', Array)
#53 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\Template->fetchView('/home/pond/publ...')
#54 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->___callParent('fetchView', Array)
#55 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->Magento\Framework\Interception\{closure}('/home/pond/publ...')
#56 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Form/Interceptor.php(416): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->___callPlugins('fetchView', Array, Array)
#57 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->fetchView('/home/pond/publ...')
#58 /home/pond/public_html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#59 /home/pond/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#60 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Form/Interceptor.php(739): Magento\Framework\View\Element\AbstractBlock->toHtml()
#61 /home/pond/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->toHtml()
#62 /home/pond/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('order_create_fo...')
#63 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('order_create_fo...')
#64 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('order_create_fo...')
#65 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('order_create_fo...', true)
#66 /home/pond/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('order_create_fo...', true)
#67 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Interceptor.php(635): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form', true)
#68 /home/pond/public_html/vendor/magento/module-backend/Block/Widget/Form/Container.php(191): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->getChildHtml('form')
#69 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Interceptor.php(115): Magento\Backend\Block\Widget\Form\Container->getFormHtml()
#70 /home/pond/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/form/container.phtml(15): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->getFormHtml()
#71 /home/pond/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/pond/publ...')
#72 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Interceptor), '/home/pond/publ...', Array)
#73 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\Template->fetchView('/home/pond/publ...')
#74 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->___callParent('fetchView', Array)
#75 /home/pond/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->Magento\Framework\Interception\{closure}('/home/pond/publ...')
#76 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Interceptor.php(403): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->___callPlugins('fetchView', Array, Array)
#77 /home/pond/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->fetchView('/home/pond/publ...')
#78 /home/pond/public_html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#79 /home/pond/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#80 /home/pond/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Interceptor.php(726): Magento\Framework\View\Element\AbstractBlock->toHtml()
#81 /home/pond/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->toHtml()
#82 /home/pond/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('order_content')
#83 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('order_content')
#84 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('order_content')
#85 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('order_content', true)
#86 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('order_content')
#87 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#88 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#89 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#90 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#91 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#92 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#93 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#94 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#95 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#96 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#97 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#98 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#99 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#100 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#101 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#102 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#103 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#104 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#105 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#106 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#107 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#108 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#109 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#110 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#111 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#112 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#113 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#114 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#115 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#116 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#117 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#118 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#119 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#120 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#121 /home/pond/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#122 /home/pond/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#123 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#124 /home/pond/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#125 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#126 /home/pond/public_html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#127 /home/pond/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#128 /home/pond/public_html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#129 /home/pond/public_html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#130 /home/pond/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#131 /home/pond/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#132 /home/pond/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#133 /home/pond/public_html/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#134 {main}

**Comment by wsajason** [comment]
Hi,

We have more detailed instructions that will be uploaded to our KB soon but in the meantime you will need to edit the eav_attribute database table and remove the value of the source_model for the attribute code "destination_type".

**Comment by chattertech** [comment]
I did that but then when i try and create a new order i get this...

![screen-shot-2018-08-15-at-5 38 24-am](https://user-images.githubusercontent.com/38303191/44149120-bcefd06c-a04f-11e8-8bcd-4198de7e6db2.jpg)

**Comment by wsajason** [comment]
Judging by the display you may need to re-deploy the static content and refresh cache and compiler.
