### ISSUE TITLE
Error on MAC

### ISSUE THREAD

**Issue by wsajason** [shipperhq/module-shipper#56]
When we use the ship to multiple addresses option on our site, shipperHQ is throwing a fatal error, and it looks like it is caused by this change.

` PHP Fatal error:  Uncaught Error: Call to a member function getStoreId() on null in /.../vendor/shipperhq/module-shipper/src/Model/Carrier/Processor/ShipperMapper.php:311`

It appears to be that `$magentoRequest->getQuote()` is returning `null`.  I'm not entirely sure of the reason, but I just wanted to make you aware of this for your testing.  We are using Magento 2.2.5

Steps to reproduce:
1) Configure your store to allow shipping to multiple address on an order.
2) Sign into a customer account on the frontend.
3) Add multiple items to your cart.
4) View your cart
5) Select "Checkout with multiple addresses"
6) Choose your addresses for the items and click "Go to Shipping Information"
7) Observe error.

Result:
500 Error

Expected Result:
Expected page to select shipping options.

_Originally posted by @squeegy06 in https://github.com/shipperhq/module-shipper/commit/3d2c7f5d37fe10b5b9561507ba98544ffd290f5f#commitcomment-30695126_

**Comment by wsajason** [comment]
Hi,

Thank you for the details. This has been replicated and raised with our developers for further analysis.

**Comment by wsajosh** [comment]
@squeegy06 This issue has been resolved in the latest release. Thanks for raising, please update
