### ISSUE TITLE
Need to be compatible with m2.2.5

### ISSUE THREAD

**Issue by michaeldyl520** [shipperhq/module-shipper#57]
Install shipperhq plugin, a 400 error occurs when sorting using delivery_date.
![_ _20181015171044](https://user-images.githubusercontent.com/4518013/46941316-71a6cd80-d09d-11e8-8067-b249fd437fba.png)
Column name judgment code location:`vendor/magento/framework/Api/SortOrder.php`

You need alter `src/view/adminhtml/ui_component/sales_order_grid.xml` All column name attributes cannot contain special characters ".".

**Comment by wsajosh** [comment]
Hi @michaeldyl520 Thanks for raising this. I'm going to investigate it this week and will provide a update once I know more

**Comment by wsajason** [comment]
This has been resolved in the latest release, 20.21.6
