### ISSUE TITLE
Incorrectly States "Please Specify Shipping Method" at Checkout

### ISSUE THREAD

**Issue by pioneerathletics** [shipperhq/module-shipper#58]
### Preconditions (*)

1. Magento vers 2.1.15
2. ShipperHQ vers  20.21.2

### Steps to reproduce (*)

1. Login as a customer 
2. Add product to cart
3.  Go to checkout
4. After address is confirmed, hit the "Next" button

### Expected result (*)

1. Checkout should progress to the payment screen

### Actual result (*)

1. Message appears to "Please Specify Shipping Method" even though the only shipping method is already selected. (see screenshot)
![screen-shot-2018-10-25-at-1 08 26-pm](https://user-images.githubusercontent.com/19981272/47518472-102eed80-d859-11e8-8631-c67378aa3de8.jpg)

2. Only happens when logged in as a customer.
3. Checkout can only proceed after selecting the shipping method again, but this could lead to confusion amongst our customers since the method was already selected.

**Comment by wsajosh** [comment]
@pioneerathletics Thanks for getting in touch.

We've been unable to replicate this issue on our development environments. Can you grab the request and response please and send it over via our support email address.

http://docs.shipperhq.com/using-the-webshopapps-logger-in-magento-2/
