### ISSUE TITLE
Cannot update to version-20.21.3 via composer

### ISSUE THREAD

**Issue by pioneerathletics** [shipperhq/module-shipper#59]
Hi,

I am currently using ShipperHQ version 20.21.2 and every-time I try to run an update via composer:

```
composer update shipperhq/*
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

I’ve tried this with sites running Magento 2.1.15 and 2.2.6 respectively. Not sure if there is something within the repository making composer think 20.21.2 is the latest version?
![screen-shot-2018-11-05-at-1 09 24-pm](https://user-images.githubusercontent.com/19981272/48017931-8951fe80-e0fd-11e8-9a87-cf901519f5a3.jpg)

**Comment by wsajason** [comment]
Hi,

Packagist had not refreshed since the last update. If you try again now that will update to latest.

**Comment by pioneerathletics** [comment]
Hi @wsajason,

I have tried to update to the latest version again for Magento 2.1.15, but it's still not finding the latest 20.21.3 version:

`composer update shipperhq/*
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Generating autoload files
`

I was actually able to update for version Magento 2.2.6 but not for Magento 2.1.15. Please advise.

**Comment by wsajason** [comment]
The version of Magento should not have an impact there. This has been tested to work with 2.1.15. Your composer cache may be having an effect, however.
You can specify the latest version using the steps outlined here: https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/#Specify_a_Specific_Version_of_ShipperHQ

**Comment by pioneerathletics** [comment]
Hi @wsajason,

That worked perfectly, thank you.
