### ISSUE TITLE
Product flat table issue

### ISSUE THREAD

**Issue by SaiBerzh** [shipperhq/module-shipper#60]
https://github.com/shipperhq/module-shipper/blob/5ae9059642ce826fcf95357acdd54eac3fb2b19d/src/Model/Product/Attribute/Source/FreightClass.php#L118

Need to use `nullable` instead of `is_null`. After building product flat table, column has `not null` property

**Comment by wsajosh** [comment]
@SaiBerzh Thanks. We will fix this in the next release

**Comment by wsajosh** [comment]
Hi @SaiBerzh This has been corrected in the latest release. Thanks for bringing it to our attention
