### ISSUE TITLE
Many Issues: Magento 2.2.5

### ISSUE THREAD

**Issue by nickpiro** [shipperhq/module-shipper#61]
We have tried multiple versions/releases of this module and have not had any success.

After first installing version  20.21.7 our Admin section was blank, our checkout blank, and shipping estimate on Cart page.

When we disabled the module, and were told by Magento to run: setup:di:compile, we received this error message:
Class 'ShipperHQ\Common\Helper\AbstractConfig' not found in /chroot/home/xxxx/xxxxx/html/app/code/ShipperHQ/Shipper/Helper/Config.php on line 44

After that, we moved onto completely removing the module's code since when we ran module:status, we showed the module was disabled. Then we ran into this issue.

When you load a product on the admin, you get this error once deleting the code from app/code:
<img width="762" alt="shipperhq-error" src="https://user-images.githubusercontent.com/36938969/52674869-e75b6280-2ef2-11e9-9781-83ea21ac90a5.png">

We have since tried every release from 20.21.5 to the latest .9.

Any ideas?

**Comment by wsajason** [comment]
Hi,

Judging by the resulting message this sounds like this may have been a migration from a Magento 1 store, which included the freight class attribute. 
If the freight class attribute is present and no longer required you can remove the source model via the steps provided here: https://docs.shipperhq.com/migrating-shipperhq-extension-magento1-magento2/

If you still require the freight functionality we can provide you with credentials required to install the freight module. Please send an email or use the [contact us](https://shipperhq.com/contact) option from our website and we can get those sent out.

Installation troubleshooting steps can be found in the article below. The steps under "class not found" cover most discrepancies as it "refreshes" the installation.
https://docs.shipperhq.com/troubleshooting-magento-2-installations/

**Comment by nickpiro** [comment]
This is a fresh install of Magento 2. Not a migration. The module was freshly downloaded from Magento Connect two weeks ago. 

This answer doesn't explain any of the issues I am having. It seems you just close issues to not have them listed as open.

**Comment by wsajason** [comment]
Please confirm that the [steps provided](https://docs.shipperhq.com/troubleshooting-magento-2-installations/#Class_Not_Found) have been followed.
The common module, if not already installed via the requirements, can be installed separately using:
_composer require shipperhq/module-common_

**Comment by nickpiro** [comment]
@wsajason installing Common caused an even bigger disruption. I had to go into the config.php file in /etc/ and disable the module because it took down our website immediately.

This is the error when we ran setup:upgrade after installing common. When I looked in the setup_module table, the module was not listed, it was listed in the /etc/config.php file which I was ultimately able to change the '1' to '0' and disable it.

Seems it's looking for a similar file, which is why I can't delete this from my system. The only way I think I'd be able to delete it is to remove ShipperHQ_Shipper from setup_module, MAYBE. I haven't tried that just yet.

PHP Fatal error:  Class 'ShipperHQ\Lib\Checkout\AbstractService' not found in /chroot/home/xxx/xxx/html/app/code/ShipperHQ/Common/Model/Checkout/Service.php on line 45

This thing is loaded with errors, I'm not sure how no one else is not having these issues. Our installation has barely any customization in regards to the theme. Definitely none in the core.

**Comment by nickpiro** [comment]
Also,

When I tried doing the link you sent above, for TestCase not found (Compiler Error), it recommends deleting the "test" directory from the ShipperHQ, all sorts of more errors. I cannot get rid of this module! We are unable to install, uninstall or use this module. What's up with the code?! This could not be just us. I installed this via ZIP, I'm glad I did not via composer or I would have serious issues.

**Comment by wsajason** [comment]
Hi,

Thank you for the full details. The ZIP of the shipper-module repo does not include all modules, which is why these discrepancies are occurring. As detailed in the installation guide [here](https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/#Manual_Installation), the ZIP located in the "ZIP" subdir includes all required modules.
We do not recommend installing via ZIP as Composer is easier to manage/update, pulls in all required modules and follows Magento 2 standards.

The full list of modules are:
https://github.com/shipperhq/module-shipper
(Composer automatically pulls in the below)
https://github.com/shipperhq/module-common
https://github.com/shipperhq/module-logger
https://github.com/shipperhq/library-shipper
https://github.com/shipperhq/library-ws

For reference the full uninstallation steps are detailed in our [uninstall guide](https://docs.shipperhq.com/disable-uninstall-magento-extension/). Removing the files manually does not remove all installed components.

**Comment by nickpiro** [comment]
That makes SO much sense. Thank you. We usually install modules via zip
because M2 is always giving issues with composer installs and the updates
have been killing us.

In regards to the uninstall:

I've deleted all of the attributes associated to ShipperHQ minus the
destination_type. When I went into eav_attribute, the only attribute left
for ShipperHQ was destination_type. I changed 'is_user_defined' to 1, but
this attribute does not display in the backend of the website after this.

Should I delete destination_type directly from the database?

In regards to core_config_data, there does not seem to be any reference to
ShipperHQ.

Although, there are tables in the database:

   - shipperhq_order_detail
   - shipperhq_order_detail_grid
   - shipperhq_order_item_detail
   - shipperhq_order_packages
   - shipperhq_order_package_items
   - shipperhq_quote_address_detail
   - shipperhq_quote_address_item_detail
   - shipperhq_quote_item_detail
   - shipperhq_quote_packages
   - shipperhq_quote_packages_items
   - shipperhq_synchronize
   - shipperhq_tablerate

Should I delete these tables above?

I've deleted all attributes BUT the destination_type in the database. When
I remove the module directory, I still receive an error on the backend.
Would this be related to not deleting this attribute?

**Comment by wsajason** [comment]
Hi,

Reinstalling the module from [the full ZIP](https://github.com/shipperhq/module-shipper/tree/master/ZIP) will resolve all missing aspects. You can then [re-run the SQL install steps](https://docs.shipperhq.com/resolve-failed-sql-run-magento/) to ensure all db entries are present.

Alternatively, deleting attributes from the admin panel is generally the recommended approach as it removes the possibilities of an incorrect delete statement or not updating related tables, etc.
Removing the attribute manually should resolve the remaining aspects, though we **strongly** recommend backing up the database prior to making any changes. The shipperhq database tables can optionally be removed; the SHQ tables should have no effect on the store.

**Comment by wsajason** [comment]
As we have not heard back for some time I assume that this is resolve and will close the issue. If you have further queries regarding the installation you can comment here or via email.

**Comment by brampta** [comment]
Hi, Just in case it helps someone I had a similar problem. I found that somehow ShipperHQ installs some attributes when you run it on your Magento2 install but when you remove the ShipperHQ module it breaks the site. I found that the solution is to remove the problematic attributes from the database.

`DELETE FROM eav_attribute WHERE attribute_code IN ( 'shipperhq_shipping_group', 'shipperhq_warehouse', 'shipperhq_shipping_fee', 'shipperhq_handling_fee', 'shipperhq_volume_weight', 'shipperhq_declared_value', 'shipperhq_dim_group', 'shipperhq_poss_boxes', 'shipperhq_malleable_product', 'shipperhq_master_boxes', 'shipperhq_availability_date', 'destination_type', 'freight_class', 'shipperhq_nmfc_class', 'must_ship_freight', 'shipperhq_nmfc_sub' )`

https://magento.stackexchange.com/questions/256641/deleted-shipperhq-module-causing-error-in-all-customers-section-of-magento-2/284135#284135

**Comment by wsajason** [comment]
Hi @brampta 
Thank you for adding.
Just to clarify, those are the steps from our [uninstall guide](https://docs.shipperhq.com/disable-uninstall-magento-extension/#How_to_Uninstall_the_ShipperHQ_Extension-2). The attributes listed on the article will be updated as and when any attributes are added to the modules.
