### ISSUE TITLE
Missing references between tables

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [shipperhq/module-shipper#79]
I noticed what some tables do not have a reference to the parent tables. For example:
 
- table `shipperhq_quote_item_detail` does not have a reference with quote_item `table` by `quote_item_id` field
- table `shipperhq_quote_address_detail` - relation with `quote_address` table
- table `shipperhq_quote_packages` -  with `quote_address` table

So, I have a lot of unused data on the project when old quotes removed, but `shipperhq_quote_` tables still have data for removed quotes.

Maybe, it makes sense for some reason, please, explain.

**Comment by wsajosh** [comment]
Hi @OleksiyOleksiyovych Thanks for raising this and apologies that you didn't get a reply sooner! We've been discussing this internally since you've raised it. We're going to look into adding some foreign keys within the next few weeks. I'll update here once its available.

**Comment by wsajosh** [comment]
Hi @OleksiyOleksiyovych 

This has been addressed in the latest release. Thanks very much for raising the issue.
