### ISSUE TITLE
Error Message at Checkout - Warning: strtolower() expects parameter 1 to be string

### ISSUE THREAD

**Issue by KernelKorn** [shipperhq/module-shipper#82]
Magento Enterprise 2.4.1
PHP 7.4
Current Module Version 20.39.5

On checkout, the error below appears after clicking the next button on the shipping step when using a saved address. 

[Video example of issue](https://github.com/shipperhq/module-shipper/files/5631093/ship.mp4.zip)
```
[2020-12-01 20:14:38] report.CRITICAL: Report ID: webapi-5fc6a42ea5923; Message: Warning: strtolower() expects
 parameter 1 to be string, array given in /vendor/shipperhq/library-shipper/src/Type/BaseOption.php on line 128 {"exception":"
[object] (Exception(code: 0): Report ID: webapi-5fc6a42ea5923; Message: Warning: strtolower() expects parameter 1 to be
 string, array given in /vendor/shipperhq/library-shipper/src/Type/BaseOption.php on line 128 at 
/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Warning: strtolower() expects parameter 1 
to be string, array given in /vendor/shipperhq/library-shipper/src/Type/BaseOption.php on line 128 at 
/vendor/magento/framework/App/ErrorHandler.php:61)"} []
```

I checked `vendor/shipperhq/library-shipper/src/Type/BaseOption.php` at line 128, the address attribute `destination_type` is a dropdown, so `$shippingOptions[] = ['name'=> $option, 'value' => strtolower($optionValues[$option])]` causes the error since `$optionValues[$option]` is an array instead of a string.

I updated the attribute to not show on the frontend which has fixed the issue for now. But I was not sure if that would break something else with the module.

**Comment by ibraheemnabeelfauzi** [comment]
Hello @KernelKorn apologize for the delays here. 

This has been fixed in the latest extension release, please go ahead and upgrade to version 20.39.8 and you should be solid to go: https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/#Updating_Existing_Installation
