### ISSUE TITLE
"Ship here" button doesn't disappear for already selected address / various templates need updating

### ISSUE THREAD

**Issue by erfanimani** [shipperhq/module-shipper#87]
I.e. the [shipping address renderer](https://github.com/shipperhq/module-shipper/blob/master/src/view/frontend/web/template/shipping-address/address-renderer/default.html) has had [quite a few changes from upstream](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Checkout/view/frontend/web/template/shipping-address/address-renderer/default.html). I tried diffing it to create a PR to add upstream changes, but they seem totally different for some reason.

One issue is that the "Ship here" button doesn't disappear when it's selected, see the added `<!-- ko if: (!isSelected()) -->` condition wrapped around the ship here button.

**Comment by wsajosh** [comment]
@erfanimani Thanks for raising this. Its resolved in the latest release. We've gone ahead and updated the other template files as well.

**Comment by erfanimani** [comment]
Awesome — thanks @wsajosh.
