### ISSUE TITLE
Error on every page due to invalid etc/events.xml file

### ISSUE THREAD

**Issue by redboxmarcins** [shipperhq/module-shipper#9]
Got error:

```
Invalid XML in file /var/www/magento/vendor/shipperhq/module-shipper/src/etc/events.xml:
Element 'config': Missing child element(s). Expected is ( event ).
Line: 8
```

As events.xml cannot contain empty config declaration

This was done in commit https://github.com/shipperhq/module-shipper/commit/76eda29ddda95741c5cda6c3fd4902d04a767131

**Comment by wsagen** [comment]
Resolved in version 20.0.15 - please update
