### ISSUE TITLE
Incorrect form key in synchronize table

### ISSUE THREAD

**Issue by MagicLegend** [shipperhq/module-shipper#91]
Hi,

In the `Synchronize with ShipperHQ` table, we are having the issue that the incorrect form key gets appended to the urls, making them unusable. Clicking them will throw the `Invalid security or form key. Please refresh the page.` error. I'm not 100% sure if this is a configuration error on our end, or just a bug in the extension.

![image](https://user-images.githubusercontent.com/3169104/111146143-c5c97b00-8591-11eb-8ee9-2e816a7266ea.png)

If more information is required, please let me know.

**Comment by ibraheemnabeelfauzi** [comment]
Hi @MagicLegend please send us a screencast to support@shipperhq.com with the login details and Magento admin access./SSH access. (I'll get DB access from there in case I need it)  
Also, I need to know: is this a multi-website Magento store? If so can you tell me what key is synched to which site in Magento as well? 

Once I get these details I'll check and be able to advise further as we never had reports of any other clients reporting that.

**Comment by MagicLegend** [comment]
Hi @ibraheemnabeelfauzi 

Thank you for your response. I have just sent out an email to the given email address about this issue. I've included answers to your questions there as well. Let's continue our conversation there.
