### ISSUE TITLE
Class ShipperHQ\WS\PostOrder\Placeorder\Request\PlaceOrderRequestFactory does not exist

### ISSUE THREAD

**Issue by jerome-rakotomanga** [shipperhq/module-shipper#92]
Hello, 

While trying to compile (`setup:di:compile` in a Magento 2.3.4 website), I'm facing an error : 

Class ShipperHQ\WS\PostOrder\Placeorder\Request\PlaceOrderRequestFactory does not exist

Module version : "version": "20.41.0",

Library ShipperHQ\WS is well defined in composer dependencies (require "shipperhq/library-ws": "^20.4" => using 20.4.1), but this version of library does not contain the missing class.

**Comment by ibraheemnabeelfauzi** [comment]
Hey @jerome-rakotomanga 
Please go ahead and upgrade to extension version 20.41.1 and this will be resolved. Here are the instructions on how to upgrade this: https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/

**Comment by msyhr** [comment]
> Hey @jerome-rakotomanga
> Please go ahead and upgrade to extension version 20.42.0 and this will be resolved. Here are the instructions on how to upgrade this: https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/

This is wrong. Updating to the newest version available (M2 2.4.2) breaks compilation. See screenshot.
![Screenshot from 2021-03-29 23-53-13](https://user-images.githubusercontent.com/22968596/112935934-6ec3ba00-90ea-11eb-9eb0-90ebfa3f61c8.png)

**Comment by jerome-rakotomanga** [comment]
> Hey @jerome-rakotomanga
> Please go ahead and upgrade to extension version 20.42.0 and this will be resolved. Here are the instructions on how to upgrade this: https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/

Hello @ibraheemnabeelfauzi,

Unfortunately, the last release does not solve the issue : https://github.com/shipperhq/module-shipper/compare/20.41.1...20.42.0

You need : 
- either to update ShipperHQ\WS module to add missing Helper class
- or remove references to ShipperHQ\WS\PostOrder\Placeorder\Request\PlaceOrderRequestFactory

Regards,

PS: As a quick fix, I froze the module in composer.json to the last working version "shipperhq/module-shipper": "20.40.2",

**Comment by wsajosh** [comment]
@jerome-rakotomanga Sincere apologies about this, I'm the developer that was working on this. Please update to 20.42.1 which should pull in library-ws to 20.5.0 which will resolve this issue

**Comment by jerome-rakotomanga** [comment]
Hello @wsajosh, 

When running compilation (`setup:di:compile`) I still have an error, but a different one  : 

![image](https://user-images.githubusercontent.com/11244473/112986147-6f4b6780-9161-11eb-8345-fbaea8df2970.png)

Regards,

**Comment by wsajosh** [comment]
@jerome-rakotomanga Thanks very much. I've updated our test plan here as clearly something went wrong. If you update to 20.42.2 it will resolve it. I've carried out the same steps as you and I'm seeing no issues now

**Comment by jerome-rakotomanga** [comment]
Thank you @wsajosh, last version `20.42.2` solved the issue. I haven't compilation error anymore.
