### ISSUE TITLE
Incompatible with patch MDVA-33289  from magento

### ISSUE THREAD

**Issue by leedyche** [shipperhq/module-shipper#95]
Hi Guys, when using braintree payments there is an issue in magento 2.4.1 (possibly earlier) that when getting to the payment section in the checkout you see javascript printed out after the street line of the address

magento released this patch https://support.magento.com/hc/en-us/articles/360058863531-MDVA-33289-Magento-patch-Javascript-in-address-at-checkout

the shipperhq/module-shipper overwrites the small change this patch makes and basically undoes the patch

Ive greated a fork / pr with the change i had to make to get this to work for me

hope it helps someone else

https://github.com/leedyche/module-shipper

thanks

**Comment by wsajosh** [comment]
Hey @leedyche 

Thanks for raising the issue. We've got it in code review right now.

**Comment by TravisBernard** [comment]
This should be resolved as of the 20.43.2 release. Thank you for the report and for the PR.
