### ISSUE TITLE
manifest.js not loading on checkout

### ISSUE THREAD

**Issue by oobehub** [shipperhq/module-shipper#96]
The console error i get on the checkout page is:
Loading failed for the <script> with source “https://XXXXX/pub/static/frontend/XXXXX/XXXXXX/en_US/ShipperHQ_Shipper/images/carriers/manifest.js”.

When i go to the module directory in the vendor folder, the directory for images/carriers/ is there, but the manifest.js is not.

The result is a forever spinning wheel on checkout, and "Shipping Not yet calculated" in the Summary sidebar.

**Comment by oobehub** [comment]
I just copied the contents of that folder from here into my own install.  I'm not sure how those files went missing.

**Comment by ibraheemnabeelfauzi** [comment]
Hi @oobehub could you please tell us what you were doing exactly and that you followed the instructions on this document: https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/ if you were installing the extension? 

Thank you.
